# Generated by Django 3.0.8 on 2020-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='DEFAULT SUBJECT', max_length=140),
            preserve_default=False,
        ),
    ]
